//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace int422_123b24.Database
{
    internal partial class int422_123b24Entities : ObjectContext
    {
        public const string ConnectionString = "name=int422_123b24Entities";
        public const string ContainerName = "int422_123b24Entities";
    
        #region Constructors
    
        public int422_123b24Entities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public int422_123b24Entities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public int422_123b24Entities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<author> authors
        {
            get { return _authors  ?? (_authors = CreateObjectSet<author>("authors")); }
        }
        private ObjectSet<author> _authors;
    
        public ObjectSet<comment> comments
        {
            get { return _comments  ?? (_comments = CreateObjectSet<comment>("comments")); }
        }
        private ObjectSet<comment> _comments;
    
        public ObjectSet<student> students
        {
            get { return _students  ?? (_students = CreateObjectSet<student>("students")); }
        }
        private ObjectSet<student> _students;

        #endregion
    }
}
